default_config:

logger:
#  default: info
  default: warning
  logs:
    custom_components.ev_smart_charging: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:

template:
  - sensor:
      - name: "my_price_sensor"
        state: 123.45
        attributes:
          prices_today: >
            [
              {
                "time": "2023-12-31 00:00:00+01:00",
                "price": 120.00
              },
              {
                "time": "2023-12-31 01:00:00+01:00",
                "price": 121.00
              },
              {
                "time": "2023-12-31 02:00:00+01:00",
                "price": 122.00
              },
              {
                "time": "2023-12-31 03:00:00+01:00",
                "price": 123.00
              },
              {
                "time": "2023-12-31 04:00:00+01:00",
                "price": 124.00
              },
              {
                "time": "2023-12-31 05:00:00+01:00",
                "price": 125.00
              },
              {
                "time": "2023-12-31 06:00:00+01:00",
                "price": 126.00
              },
              {
                "time": "2023-12-31 07:00:00+01:00",
                "price": 127.00
              },
              {
                "time": "2023-12-31 08:00:00+01:00",
                "price": 128.00
              },
              {
                "time": "2023-12-31 09:00:00+01:00",
                "price": 129.00
              },
              {
                "time": "2023-12-31 10:00:00+01:00",
                "price": 130.00
              },
              {
                "time": "2023-12-31 11:00:00+01:00",
                "price": 131.00
              },
              {
                "time": "2023-12-31 12:00:00+01:00",
                "price": 132.00
              },
              {
                "time": "2023-12-31 13:00:00+01:00",
                "price": 133.00
              },
              {
                "time": "2023-12-31 14:00:00+01:00",
                "price": 134.00
              },
              {
                "time": "2023-12-31 15:00:00+01:00",
                "price": 135.00
              },
              {
                "time": "2023-12-31 16:00:00+01:00",
                "price": 136.00
              },
              {
                "time": "2023-12-31 17:00:00+01:00",
                "price": 137.00
              },
              {
                "time": "2023-12-31 18:00:00+01:00",
                "price": 138.00
              },
              {
                "time": "2023-12-31 19:00:00+01:00",
                "price": 139.00
              },
              {
                "time": "2023-12-31 20:00:00+01:00",
                "price": 140.00
              },
              {
                "time": "2023-12-31 21:00:00+01:00",
                "price": 141.00
              },
              {
                "time": "2023-12-31 22:00:00+01:00",
                "price": 142.00
              },
              {
                "time": "2023-12-31 23:00:00+01:00",
                "price": 143.00
              }
            ]
          prices_tomorrow: None
          prices_tomorrow2: >
            [
              {
                "time": "2024-01-01 00:00:00+01:00",
                "price": 120.00
              },
              {
                "time": "2024-01-01 01:00:00+01:00",
                "price": 121.00
              }
            ]

